import Head from 'next/head'
import Navbar from '@/components/Navbar'
import { Inter } from '@next/font/google'
import Tabs from '@/components/Tabs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Chords App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main>
        <h1>Guitar Tabs</h1>
        <Tabs />
      </main>
    </>
  )
}
